package main

import (
	"testing"
)

func isValid(S string) bool {
	return isValidStack(S)
}

//泛用的字符串替换思路解法
func isValidReplace(S string) bool {
	res := replaceString([]byte(S), "abc")
	if len(res) > 0 {
		return false
	}
	return true
}
func replaceString(origin []byte, search string) []byte {
	if len(origin) < len(search) {
		return origin
	}
	lo := len(origin) - 1
	n := 0
	flag := false
	for n < lo {
		if n+2 > lo {
			break
		}
		tmp := make([]byte, 3)
		tmp[0] = origin[n]
		tmp[1] = origin[n+1]
		tmp[2] = origin[n+2]

		if string(tmp) == search {
			if n+3 <= lo {
				origin = append(origin[:n], origin[n+3:]...)
			} else {
				origin = origin[:n]
			}
			lo = len(origin) - 1
			flag = true
		}
		n++
	}
	if !flag {
		return origin
	}
	return replaceString(origin, search)
}

//使用堆栈 需要指定字符匹配 性能很好
func isValidStack(S string) bool {
	stack := make([]rune, 0)

	for _, c := range S {
		if c == 'c' {
			if len(stack) > 1 && stack[len(stack)-1] == 'b' && stack[len(stack)-2] == 'a' {
				stack = stack[:len(stack)-2]
			} else {
				return false
			}
		} else {
			stack = append(stack, c)
		}
	}
	return len(stack) == 0
}

func TestIsValid(t *testing.T) {
	var S string
	var exp, res bool
	S = "aabcbc"
	exp = true
	res = isValid(S)
	if exp != res {
		t.Error(exp, "not equal", res)
	}

	S = "abcabcababcc"
	exp = true
	res = isValid(S)
	if exp != res {
		t.Error(exp, "not equal", res)
	}

	S = "cbabcacbaabccaabbabcabcbcabaccacaaabbacbaabbaaaaaabbcabacbcccaacbbcaaabbbcababcccaaaacbaacbbbbbbbabbcabcbabaaacabcccbacaabbaccabacccaacbbccbacbaacacaccbaabcaacabbabaccccccaabcbbbccacbccccbabbbaccbbacbcaaabcacbaccbcabcacbaccabaaaaaabbbabccacccaaaabaccbbcbcbcccbcbccbbbbccbbaaaaacbacbbbbacaaccbaacaacbacccbaabbbabacccbaccabbbabbcccbcbaacbaabbccbbbcaccbcccbcabaabaabbbbaaaacbabbacbbacbbcccbbabbcabccbaccbbacbcbbcbbacacbbcabccabcabacbcbabccbacabaabbcaabccbaaaccababaaacbaacccbbbacccbacbbccccbaccabcccbccbacbbbabccccaccaaaaccbcaaababaacbccbbaabbbacabbbabcbcbbbabacbcccabccbcbaccbacacbabacbccacbcbbcccaaaabbbacccbcabbbcbccaaaccbaabbabaabbccabbacaabcbbabbaccbabbcccacaccbccabcbbbacbbaaccbcacacaaaccbcabbbbccaacacababccbacbbcccbacbbbcbbcbccacccbcacbcaccbaaaaccbcbcbaacabaaccacaabbccbababccabbabccaabbccaaacbbacbcaabaabbabbcbbcbaaabccabcbbbabbaaccccccbbbbacccaabaccbccaacabbacacaacbcaabacbaabbcbcaacbacacaaaacbbcabaccabcabbabaabccabacbbbacabcccccacabaabcabccacbbaacbbbbcaabaaabcbabbaabaaabbcabcbccabcbacbabccbbabcabaabcbbbbabbbcabcbcbabaccbaaaababbbcaccaacbbbbccbbbbcaaccacabcaacbcabbbbcccabaaccbbcacacabcbbbccacbacaabbbaccccabbcccbbacbabacabcaabcabbbaaabcbbababacbbbcbbaaabbbccbccbabaccbbcbcabcaabcabbacababbacbacbbcbacabaccaacccccabaacbbbcabbbabbaaabccccbbabcacabbcababccccaaccbbbbcbabacbaacbacbabbbbaabcbbaacbbcbcbacbbacaccaccbcbbcabacbbbbbbbcbcaacbcaaabccabaaacababcbaabbcbbababaaccbccacbcccbabbcccabccaabcabbbabbbbabbcbabbbbabcbccacbbcbababaaccbacbabcbcaccaccccccaaaacabcaacabccabcabaacbccbaaabbacbabaaacabbbcbbabcbacbbcbabacabaaacbcbcabcccacaabaababbcaaacaabcccbaacbaaaabbcacaaaaacabcbcabaabcabbcabbaaaaaccaaaccabaacabcccabaacabbbcaaaaaccbcbbabccaaaacbbbaabcabcbcbacbacaabcccccacbbcccbcbabbcbaccbcabcbbaabcbacbbacbaacbccbbcacacabcbcbccacaaaacbcaccbbbbccacaabcacbababacbacaaaabccbbbabacacbbbbcacbacbbacccbaabbcbacbbbbcbcabbbcabbcbcabcbcabcccbabaaacbcacbbabcbbabbbbacbcbaacbcbbbabacbcbbacabcbcbacbaaaabcbbbbaccaacbbbacabcbccbacbacaaacccbbbacbccbbaabaabbcbcabaaabbcbabcaaccccbcbbaccaabaacbcaabcaaacbbaabbababacbbaacbabcbccabbbccbcabcbbbbabbcabaabcabbbabaacaacaaccbccccaaabaaccbabcbaaaabaabbbccbbbbbaabaaacbaaccbcbcaabaccbcacbcbcabbacaacbcbabcabbcaabcbccbbabbccbbaaaccaabccacbbbbcbbacccbbcccbacaccacaccabacababcbbbbaaaabccbababbccbacccbcbcacbacaabcacabbbacbbacabaabcbbababbabababccbccbbbcabcabccacbbaacbaacacaacbbcaccbbacbaaaacccaabbbbbbabaaacbbaaccbbaabcbbcbbcabbacaccacaaaacbababacbaccaccacaaabccacbcbcbababbbcaaaabbbcaaaaccccbaaaacbcbcaacabaabcbbcabacabaccbbccccaaabbccbccbacaabacabbaacacbcbbaababbaabcbcbbaaacbabccbcbcbcacbcbbabcbcccbcaabcbaababbcababcbacbcabbacaaaacaacaaccbabcbcbcccbbcbcabccbbbacbbaaabbbbabcbabccabaaabbbabbbacaabcbccaaaacbbabcbaabcbaabcbbaaaccaabbccaaaaacaaabbaccbaaaccbacbbabcccbcabcabcbacabaaccbbbcacccbacacaccabcabcaacacbbabbbbbbcccbcacaabaccaaaccbcccccbbabccaaaccbaccababccababccccbcbaaacaababaabcbccabcaaaccbcbbbabbacabcbccabacacccacaabccbabbccccabbcbaccbcbcbababbabcabbacbcbacaabccbaaaccacbaacccbaccbcbbbcacbbabcbbbbbccbccbcaaabccacabbcacabcbacbbcaabcccbbcbabcbaacacaabbcbabcbcaaaaacabcabbccccbcacbacaababbbacccbabbacbabbcbaabbcbcaaacababbbacacacaabcaabbaabbaccccbaaabaacabbccccbbcabaaaabcacbaabcbbbcccaabcaaaccbacabcccababcaacbccccaacabcacbcabbbbbccabacaccbaacbcbaabcbaaacbbbcaccabcbcacbbcbabbbaacaaacccaaaccacbcbcabbbacbbacaabcabbbcabbcabacbcabacbbbccbbbbaabaaacaaabbcbabcabacaccaacababbacaccaaaaaabccaabacbbacccaabaacabbcbcbaccacaccacabbaaccaabcaacbabbcacccbaacacccbccbaaaaaaabbbaabbcaabaccbbccbacbcacbcaaaabababbbcbcabacbbbccaacbcccbaccacbacbacccbbcbacbaccabcacbabaaccbccbbcbcaaaababbabbbcabbaabcaacbbaacccccbbcabbaccabacbbabbbcbaacbbaaccbaaaccbbaabababcacabaabcccaabaaacabccbaaaccbbcabcbcacaabbbbaabbcabbaacaaaabccbccbcabacaababaccabcbcbabaccaabaaaabcccbbcbbabaacbabacacccbcaabaabababbbcaaaacccbccacccaaabcbcacbbccbcccccabaaacaababcacbacaccbccacabbcacabbbabccaccaabbbbbbacccbacacacabbcbcccbbaacbcbcccacaaaccbccaccccbbaaacacbabaccbabbbacccabbcbbcbaacbbbcbccacaccbaccbabbbabcbcacabcbacbabcbbabaaaabaabbbbbaacccaacbbaccbcbcbccabbbabbabbbcccababbaccaabcbcacbbcacaacacabaabbcabbcccbabacbaabcccacbcbaccaaabcbbabaabbacacccbcbaacccbaaaccaacccccabacccccaaaaabbccbabccbaaacaaccaccaabbbbbccbbcaccaccacbaaccabaaacaabcbccbaaababccbccacbbccbaababaacabbaaababcaaaabababcacabacbabacaabaacbbacacbbccbcaaccabbbabcacbcbbbacbabccbcccabcaaacabcbbbacabcbccabacacacbabbababacbccaaccabccbcbaaaccbbaccaacacbacacbbabccbaaccbcbcabaccbacccacccbbbccabbcaabbbbbbcbacabcababbbcbbabbaaacbaacbabacabbcccaacccaccbcccaabccaacabcbbbcbbcacccbaacaccabbbcaccacabccacbbabccbbccabcaabaabbacabbcbaaaaabbacbaaaccabcbabbaabccbbcbaccaccabcabccbabaabbcccbcaabcacccbabacccbacaccaacbcbabacbbcacabbcccbbbcbbbaabccbacabbcaccbacacaabcbbaccbcabccababcbbabbbccbbbcbaabbcbbbcacababcccaaaaccbbbacbababbcccaabbacacbcccaacabbaacbacbabaabbaaacbbbcacaccacbabbcbcaccaaaccbbbaccaacacaacbaababacaabbbbacabccbcbbaccbccbbabcacccbcaaabccccabcbaacbcbacaaaabcacbabbcaaacbcaaaaababcaabcaaabbaaaacccaaaaaacccacababaabacabacabcabccaabccccaaaabbcacbcabacabcbabaccaacbabcbcacbabcabbaaaaccbcbbaabcaacbabbbcbccbaacacbabcbcaaacaaabccabccaacbcaacbaacbbbccccacbaccbbcccbaaaccccbaaccacbaaaabbbcccaabbacaacccbabcacabcccbaaccabaccccbbccaaaababbacbccababbacbacbbcbbbbabcccbcaaabcccbaccbbbccccccabcacaaabcbbacabacccbaccacccbabaaaacaacaaabacaacacbbcabbbbaccaabbbbbcaacabaabcacccaabbaabbabbbcabbcacbbbcbcaacccaccaaaabcbbcacbaaabbbbabaaacccccaacbcacababbbcbbbaababccbabcbacacaccbcbbbcabacabcbccabbaccbaacccacabcccacbabbbacbacaabcbccccabbcabacbbcaccabbacaccacbabcbcabbbacaacabccabcccaaaaacababccaccbbcccbbbbcccbbccabaaacbcacccacbabbabaaaacbccccbbccbbccabbcccaabcaabcbabbbacaacacbbcaccbccbcabcbccacabccbaaccaacbbbacaabbbbcabbacbaccccbabbcabbaacbcabbcacbccbbcacbbbacccaccacaabacaabbaacaccbcbbcaabaabaaaacaabbacbbabacaaaaaaacbabacabbcaabbbabaacaacbaaabbbbcabcbabacaccacbabababbcabbaabaabbcbaabccbabcbbccbbaaaacabaacabcbabcacbbbbbaabcacaccccabcacabccbcaacbccbaaabccbcbaaccbbaaccbbbbcbcabcbcccacccbaccaabaccbbabacacbcbacbcbbacabbbbacacababccbababbbbbcbcacacbbbabbcabbaaacabcbbcaabacaaaaaaccbcaccccaacccbcbbcaccabbcbacccaccaacccbbbcabbabcbcbccaabaccccaccbcbbbacbcbaacccbabbcabccbbbbbcacccbbabcbabaccbbbacbcabbaacbbbcabbabaccaaacacccaaababbbbaccacacbbaaabaabcbaccabbbcabbbcbccacbbacabababcccbbabcccabacabbaaabcbaacbbcccabbaabccabbacccaacbcabaaaaccbacbcccbacbaaaaacbbccabbaaaaaaaccbbbcbaacbbbaaaababaacccbaccaabacbcaacaacbbabcbcbbcbbbbcbaaabcccabaacabaabbbbcbaacaacabbaaacccbbcccbaacacccbacaaaaacbbabaabcccccbabaabbbbcacbccabccccbbbbacacbaaacbcccbaccbacbabccbbbccabaabcacccabbcbbccaccbbbabbbaabccabababcbbcbacbaccabbaaccaabaccbccaaacabcbbbacaabccaaacaabcccaaccbcabbccacbbacbbabcbacaccbbcbcbabcbcacaacbbbbaacabcacbaabccccbabbbccbcaaabcbaacbbaaacabbacabbacacccbbabbaabcbcccbbcbcabcbccbacaccccccccbbcbcbbabaaccbaccbcbbcabcaababacbbccbbccbccbbccaccacbaabcccbbacccbacaaaccaacbacacabcbbccacaaaaaabbabbacccbaaaaaacacacaabacacaccbaabbbccabcbbcabbcbbabcaaacbccaabbcbacaaabcbbbbbcacaabaccccccbaacacccabcbcbbccacabaabccacabbcccabbccabbcacccaccaabbcbbcbaccbbaabcbaccaaaacacbcbbbbcccabcaabbcbcbcaaccccaacaaaaccbacbcccbabbbaaacccbbccacbcbbcbabbbacccaacbcbcbaaaababcaccccbbbcccbbacbabacbcbcccccabbacbcccababcbcacccabcccacabbabbacccaabacaaacacbacaacbcabccbccbabbbacabacacacbccaacbbccbbcbaacbcbbbaacbabaacbbccbbccabacbbcbaaaacbccbcacbbabaacaaacbbbbbbaacabccbbbbaccbbcabbbbbbcbaabbbcbbccbbaaabcbaabbacabaabcbabcccccaacbaaabcbbaccbbaaccaaccccacbaacbcbbacccaacbabcaabaabbbbacbaabbcbacabcabccbcaaabbaccbaccbbababccccaaacbaabcccbbabbbbcbacbcccaaccbaabbccbccabaaabbabbbcabbbabaccabaabacbbacacbcbbbccbacbbbabccabcababcbabccbaccbccccbaabccbcacccbcbcbaacbbaaacbbcabcacaaccacabccccccaaaaaabbabccabccaccbcbbccbccbbccaaabcbbcccabcabbccaccaacbcabccbabbcbbacacabaccabcbbaaccabbbbbcaabbbaabaabbbcaaacacbbcbbccbcbbacbbcbcacaaabaaaabacabcbcaacababcbbbabacbabacccbacabcacbacabbbccacabcacbbccabcaaaccbabbbbaaabaaaacccabbacbcccbaacaacabcbbcbaaacbcbcaccaacabbcbacaaaaacbababbcbbcacacbccacbaacccaaacaacbcaaccaaacbabaccccbaaccccbbcbcccacbabbccaccaaacaababcbcaacaabacbcaabaabcbcaaacbcaaacacaccababaaacabaacccbccbababbabcccbccccbaccaaaaabcbbbbccccacaaabbbcaacbbbcacacbacabbacbcacaccacaccbacaccbaabcccbacbcaccccaaccccacbaaabacccbbabbaacabaacbbacabbabaaaabaacabccbcabaaabbbacaccbaababaccbacccaccbaabbacacccccccccacbcccacbabacaabcaaabbbaacbbcbacbabbcaaacccaababcbacbcbbbbcabacabcbbbcbcbcbabababbaabbcbcbabcbaacbbcccbccabcbaacbaaacccbccbccbbbabbaabbaaacabcaabbcbabbbcababcbbbcbabcaaaababaaaccbccababcabacaacccccabcaccaaabaacccbcbbcbaaaaabcabbcacaaabacbccbcbaaacacbbbaaaabacabbcbbabbabacbcbcbcbcaacbabaaabaccaaabbcbacbcbcabbbccbbbaaaacaaacbabacbbaccabbccbaacbcacaacabcbacccbabccbacbbcbcabaaabaaaacabacabbbaacbccbcaaabbcbbbaaaccbcbcababacaaaaaabccbcbcbbacbbcbacbaabaaccbbcbbbabacabacbcbbaaacccabbabcabacacabbccbcbcbcabacbbcbcabcaabbabbcbbbaabaaacaaacbbccbbacbcbbcbbbbbabcbabbccaabbbac"
	exp = false
	res = isValid(S)
	if exp != res {
		t.Error(exp, "not equal", res)
	}
}
